---
abstract: 'Solve ODEs using Perl and GSL v1.15+'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-GSLx-ODEIV2
no_index:
  directory:
    - t
    - inc
requires:
  parent: 0
resources: {}
version: 0.07
